name: Olympixel
version: '${project.version}'
main: prod.brainiac.olympixel.Olympixel
api-version: '1.16'

commands:
  Olympixel:
    description: "Used to run Olympixel mini game commands."
    usage: "/olympixel <SubCommand>"
    aliases: [ opx, olp ]

permissions:
  olympixel.admin:
    description: "Allows access to all Olympixel commands."
    default: op
  olympixel.player:
    description: "Allows access to player commands."
    default: true
